FROM node:12.2.0-alpine as build

WORKDIR /app

COPY . /app/

RUN npm install --silent

RUN npm run build
                    
#FROM nginx:1.16.0-alpine
FROM nginx

COPY --from=build /app/dist /usr/share/nginx/html
COPY /nginx/nginx.conf /etc/nginx/conf.d/default.conf
#Commented for deployment to heroku
# EXPOSE 80
CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
